### ISSUE TITLE
Flash zip after downloading

### ISSUE THREAD

**Issue by androidlover5842** [Grace5921/OtaUpdater#3] opened 2017-01-12 09:10 UTC
it should show option to show flash zip if it's downloaded

**Comment by AbdullahAlAsad** [comment] 2017-01-13 03:38
What about the download progress status showing. Does this apk prompt for flash the rom.zip ? I am using your project and want to contribute as I am working with aosp . Thank you for your effort and time.

**Comment by androidlover5842** [comment] 2017-01-13 06:55
it uses android's default download manager but flasher is not implemented yet .


https://github.com/Grace5921/OtaUpdater/invitations

**Comment by AbdullahAlAsad** [comment] 2017-01-13 07:03
OK, I am trying to integrate implementation of flashing rom , I will come back with the merged branch.

**Comment by androidlover5842** [comment] 2017-01-13 07:08
okay thanks

**Comment by androidlover5842** [comment] 2017-01-14 13:25
i have added it and will push changes in few mins

**Comment by AbdullahAlAsad** [comment] 2017-01-14 18:01
Great to know that, thanks. I will try it.

I am not seeing the flasher code commit. Did you add it ?

**Comment by androidlover5842** [comment] 2017-01-14 20:18
no i am not home i will push changes when i am back

**Comment by androidlover5842** [comment] 2017-01-14 20:52
it's pushed but it's at beta stage so bugs are expected

**Comment by AbdullahAlAsad** [comment] 2017-01-16 10:16
Hi, I have tried to flash. But it's not working. I am trying custom aosp rom in nexsus 5.
SCRIPT_PATH = "/cache/recovery/openrecoveryscript" ; 
in OpenScriptGenerator.java
is there anything to do with this path. 
I am using twrp recovery image. 
Thanks in advance

**Comment by androidlover5842** [comment] 2017-01-16 10:19
i have not tested those changes but it was shure they should work and cache/recovery/openrecoveryscript is used to flash rom when twrp boots

**Comment by androidlover5842** [comment] 2017-01-16 10:20
testing now

**Comment by androidlover5842** [comment] 2017-01-16 10:49
my fault sorry https://github.com/Grace5921/OtaUpdater/commit/4ef907513f4cc5cc28fc1b76a1c99952773ad91e

**Closed as completed** 2017-01-16 10:49 UTC
Labels: enhancement

**Comment by AbdullahAlAsad** [comment] 2017-01-16 11:38
still not working , it don't show any error on logcat but there is no activity assuring  flash button event 
and from adb shell I saw no file generated named as "openrecoveryscript" . May be it is not creating the shell script. should i create it manually and then try once ?

does the openrecoveryscript need an .sh extension ?

**Comment by androidlover5842** [comment] 2017-01-16 11:45
aosp is not rooted i think so and this app needs root to create file in cache

**Comment by AbdullahAlAsad** [comment] 2017-01-16 11:56
should I add 
Shell.SU.run("root");  //this line before 
Shell.SU.run("mount -o rw,remount,rw /cache");

**Comment by androidlover5842** [comment] 2017-01-16 14:16
Shell.SU.run("root"); //this line before
 what is need of this ??

**Comment by AbdullahAlAsad** [comment] 2017-01-17 02:58
to root aosp ?

**Comment by AbdullahAlAsad** [comment] 2017-01-17 05:01
Hi, Sorry to bother you again. I am getting the following error.
01-17 10:57:42.994 2579-2579/io.github.otaupdater.otaupdater E//system/xbin/su: IOException: Error running exec(). Command: [/system/xbin/su] Working Directory: null Environment: null

How can I root my custom aosp rom ?
Is this for unrooted phone ?

How the commercial phone like samsung, lge handle this ?

**Comment by androidlover5842** [comment] 2017-01-17 06:53
sorry this app needs root for now and i am working hard to make it usable on un rooted device but if you want to root your aosp rom then you can use system less root http://www.supersuroot.com/

**Comment by AbdullahAlAsad** [comment] 2017-01-17 07:16
Yes, I have tested it in rooted device. It restart successfully to recovery mood but the flash is not happening and still there is no file as openrecoveryscript in cache/recovery

**Comment by androidlover5842** [comment] 2017-01-17 07:21
okay show me log

**Comment by AbdullahAlAsad** [comment] 2017-01-17 08:32
01-17 14:29:13.011 1784-1850/io.github.otaupdater.otaupdater D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
01-17 14:29:13.053 1784-1850/io.github.otaupdater.otaupdater I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
01-17 14:29:13.055 1784-1850/io.github.otaupdater.otaupdater I/OpenGLRenderer: Initialized EGL, version 1.4
01-17 14:29:13.094 1784-1850/io.github.otaupdater.otaupdater V/RenderScript: 0xaeef1000 Launching thread(s), CPUs 4
01-17 14:29:24.521 1784-1784/io.github.otaupdater.otaupdater I/UpdateCheckReceiver: Starting
01-17 14:29:24.522 1784-1784/io.github.otaupdater.otaupdater I/UpdateChecker: Started
01-17 14:29:27.088 1784-1784/io.github.otaupdater.otaupdater I/UpdateCheckReceiver: Starting
01-17 14:29:27.089 1784-1784/io.github.otaupdater.otaupdater I/UpdateChecker: Started
01-17 14:29:27.151 1784-1784/io.github.otaupdater.otaupdater I/UpdateCheckReceiver: Starting
01-17 14:29:27.152 1784-1784/io.github.otaupdater.otaupdater I/UpdateChecker: Started
01-17 14:29:29.019 1784-2365/io.github.otaupdater.otaupdater E/RomUpdater: I/O error. AppUpdate can't check for updates.
                                                                           javax.net.ssl.SSLHandshakeException: Handshake failed
                                                                               at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:396)
                                                                               at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:103)
                                                                               at com.android.okhttp.Connection.connect(Connection.java:143)
                                                                               at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
                                                                               at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
                                                                               at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
                                                                               at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
                                                                               at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
                                                                               at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
                                                                               at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
                                                                               at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:231)
                                                                               at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                                                                               at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
                                                                               at io.github.otaupdater.otalibary.RssParser.parse(RssParser.java:42)
                                                                               at io.github.otaupdater.otalibary.UtilsLibrary.getLatestRomVersion(UtilsLibrary.java:179)
                                                                               at io.github.otaupdater.otalibary.UtilsAsync$LatestRomVersion.doInBackground(UtilsAsync.java:57)
                                                                               at io.github.otaupdater.otalibary.UtilsAsync$LatestRomVersion.doInBackground(UtilsAsync.java:13)
                                                                               at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                               at java.lang.Thread.run(Thread.java:818)
                                                                           	Suppressed: javax.net.ssl.SSLHandshakeException: Handshake failed
                                                                           		... 23 more
                                                                           		Suppressed: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0xb06d1980: I/O error during system call, Connection timed out
                                                                               at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
                                                                               at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
                                                                               			... 22 more
                                                                            Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0xb06d1980: Failure in SSL library, usually a protocol error
                                                                           error:100c543e:SSL routines:ssl3_read_bytes:TLSV1_ALERT_INAPPROPRIATE_FALLBACK (external/boringssl/src/ssl/s3_pkt.c:972 0xaacca980:0x00000001)
                                                                               at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
                                                                               at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
                                                                               		... 22 more
                                                                            Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0xb06d1980: Failure in SSL library, usually a protocol error
                                                                           error:100c543e:SSL routines:ssl3_read_bytes:TLSV1_ALERT_INAPPROPRIATE_FALLBACK (external/boringssl/src/ssl/s3_pkt.c:972 0xaacca980:0x00000001)
                                                                               at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
                                                                               at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
                                                                               	... 22 more
01-17 14:29:29.054 1784-2365/io.github.otaupdater.otaupdater D/RomUpdater: Something went wrong
01-17 14:29:29.725 1784-1784/io.github.otaupdater.otaupdater D/Found: Update Found
01-17 14:29:29.725 1784-1784/io.github.otaupdater.otaupdater D/RomUpdater: 20170217, https://www.dropbox.com/s/wp6u1xbi4y0dfu3/siempov013011341.zip, true
01-17 14:29:29.797 1784-1784/io.github.otaupdater.otaupdater D/Found: https://www.dropbox.com/s/wp6u1xbi4y0dfu3/siempov013011341.zip
01-17 14:29:29.883 1784-1784/io.github.otaupdater.otaupdater D/Found: Update Found
01-17 14:29:29.883 1784-1784/io.github.otaupdater.otaupdater D/RomUpdater: 20170217, https://www.dropbox.com/s/wp6u1xbi4y0dfu3/siempov013011341.zip, true
01-17 14:29:29.915 1784-1784/io.github.otaupdater.otaupdater D/Found: https://www.dropbox.com/s/wp6u1xbi4y0dfu3/siempov013011341.zip
01-17 14:29:34.937 1784-1784/io.github.otaupdater.otaupdater D/RomUpdater: Update Found
01-17 14:29:34.937 1784-1784/io.github.otaupdater.otaupdater D/RomUpdater: 20170217, https://www.dropbox.com/s/wp6u1xbi4y0dfu3/siempov013011341.zip, true
01-17 14:29:35.049 1784-1784/io.github.otaupdater.otaupdater D/Found: https://www.dropbox.com/s/wp6u1xbi4y0dfu3/siempov013011341.zip
01-17 14:29:35.191 1784-1784/io.github.otaupdater.otaupdater W/InputMethodManager: Ignoring onBind: cur seq=4, given seq=3
01-17 14:29:40.608 1784-1784/io.github.otaupdater.otaupdater I/DownloadBreceiver: DownloadFinished
01-17 14:29:45.931 1784-1784/io.github.otaupdater.otaupdater W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
01-17 14:30:17.630 1784-1784/io.github.otaupdater.otaupdater I//system/xbin/su: mount -o rw,remount,rw /cache
01-17 14:30:18.016 1784-1784/io.github.otaupdater.otaupdater D//system/xbin/su: END
01-17 14:30:18.037 1784-1784/io.github.otaupdater.otaupdater I//system/xbin/su: touch /cache/recovery/openrecoveryscript
01-17 14:30:18.321 1784-1784/io.github.otaupdater.otaupdater D//system/xbin/su: END
01-17 14:30:18.348 1784-1784/io.github.otaupdater.otaupdater I//system/xbin/su: echo 'install /storage/emulated/0/Download/siempov013011341.zip ' > /cache/recovery/openrecoveryscript
01-17 14:30:18.646 1784-1784/io.github.otaupdater.otaupdater D//system/xbin/su: END
01-17 14:30:18.660 1784-1784/io.github.otaupdater.otaupdater I//system/xbin/su: echo 'install wipe data ' >> /cache/recovery/openrecoveryscript
01-17 14:30:18.940 1784-1784/io.github.otaupdater.otaupdater D//system/xbin/su: END
01-17 14:30:18.965 1784-1784/io.github.otaupdater.otaupdater I//system/xbin/su: echo 'install wipe cache ' >> /cache/recovery/openrecoveryscript
01-17 14:30:19.245 1784-1784/io.github.otaupdater.otaupdater D//system/xbin/su: END
01-17 14:30:19.265 1784-1784/io.github.otaupdater.otaupdater I/Choreographer: Skipped 99 frames!  The application may be doing too much work on its main thread.

**Comment by androidlover5842** [comment] 2017-01-17 08:43
can we talk on hangouts ?

**Comment by godslave05** [comment] 2017-01-17 09:21
yah sure, i was going to tell you that. my id is : info.alasad@gmail.com
